### PR TITLE
Use latest reqwest (v0.9)

### PR DESCRIPTION
**Pull request by MikailBag**
This version supports opensll v1.1.1

### CODE REVIEW

**Comment by kpp** [comment]
Hey!
We haven't setup any CI, so merging this PR will take some time to check whether it actually works (at least builds correctly). Rr you can setup CI and push it.

**Comment by kpp** [comment]
I enabled the repo in TravisCI. Do a force push please

**Comment by MikailBag** [comment]
On my machine, it builds successfully.
BTW, does it support OPENBW?

**Comment by kpp** [comment]
> BTW, does it support OPENBW?

Last time I managed to build, link and launched it. The bot could send a message, but there were no any units displayed on the screen. No start units (slaves), no CCs.

See docs: https://github.com/RnDome/bwapi-c#usage-on-linux-with-gcc-for-bwapilauncher

**Comment by MikailBag** [comment]
Hmm, it seems Travis won't run tests until I update PR somehow.
So, I will rollback Travis integration I have set up for my fork.

**Comment by kpp** [comment]
> Hmm, it seems Travis won't run tests until I update PR somehow.

Do:

```
git commit --amend
# Save the old message

git push $YOUR_REMOTE HEAD -f
```

**Comment by kpp** [comment]
Will you push CI again?

**Comment by MikailBag** [comment]
Maybe I should recreate PR?

**Comment by MikailBag** [comment]
In order to recreate, I need close this

**Comment by kpp** [comment]
You don't need to recreate a PR. Contact us on https://gitter.im/kpp/bwapi-c

**Pull request closed without merging**
